{========================================================================================
  Include file : poci_lcltyphonversion
  Description : Pascal Object Compiler Informations

                Purpose a way to get compiler informations in builded project

  Author : Frédéric Libaud
  **************************************************************************************
  History
  --------------------------------------------------------------------------------------
  2024 03 07 - Création
 ========================================================================================}

{$ifdef CT_VERSION}
  {$if LCL_FULLVERSION = 8030000}
  FRAMEWORK_VERSION = '8.0.3.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 8020000}
  FRAMEWORK_VERSION = '8.0.2.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 8010000}
  FRAMEWORK_VERSION = '8.0.1.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 8000000}
  FRAMEWORK_VERSION = '8.0.0.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 7090000}
  FRAMEWORK_VERSION = '7.0.9.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 7080000}
  FRAMEWORK_VERSION = '7.0.8.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 7070000}
  FRAMEWORK_VERSION = '7.0.7.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 7060000}
  FRAMEWORK_VERSION = '7.0.6.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 7050000}
  FRAMEWORK_VERSION = '7.0.5.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 7040000}
  FRAMEWORK_VERSION = '7.0.4.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 7030000}
  FRAMEWORK_VERSION = '7.0.3.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 7020000}
  FRAMEWORK_VERSION = '7.0.2.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 7010000}
  FRAMEWORK_VERSION = '7.0.1.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 7000000}
  FRAMEWORK_VERSION = '7.0.0.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 6090000}
  FRAMEWORK_VERSION = '6.0.9.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 6080000}
  FRAMEWORK_VERSION = '6.0.8.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 6070000}
  FRAMEWORK_VERSION = '6.0.7.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 6060000}
  FRAMEWORK_VERSION = '6.0.6.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 6050000}
  FRAMEWORK_VERSION = '6.0.5.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 6040000}
  FRAMEWORK_VERSION = '6.0.4.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 6030000}
  FRAMEWORK_VERSION = '6.0.3.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 6020000}
  FRAMEWORK_VERSION = '6.0.2.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 6010000}
  FRAMEWORK_VERSION = '6.0.1.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 6000000}
  FRAMEWORK_VERSION = '6.0.0.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 5090000}
  FRAMEWORK_VERSION = '5.0.9.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 5080000}
  FRAMEWORK_VERSION = '5.0.8.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 5070000}
  FRAMEWORK_VERSION = '5.0.7.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 5060000}
  FRAMEWORK_VERSION = '5.0.6.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 5050000}
  FRAMEWORK_VERSION = '5.0.5.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 5040000}
  FRAMEWORK_VERSION = '5.0.4.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 5030000}
  FRAMEWORK_VERSION = '5.0.3.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 5020000}
  FRAMEWORK_VERSION = '5.0.2.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 5010000}
  FRAMEWORK_VERSION = '5.0.1.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 5000000}
  FRAMEWORK_VERSION = '5.0.0.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 4092000}
  FRAMEWORK_VERSION = '4.0.9.2000';
  {$endif}
  {$if LCL_FULLVERSION  = 4090000}
  FRAMEWORK_VERSION = '4.0.9.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 4080000}
  FRAMEWORK_VERSION = '4.0.8.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 4070000}
  FRAMEWORK_VERSION = '4.0.7.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 4060000}
  FRAMEWORK_VERSION = '4.0.6.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 4050000}
  FRAMEWORK_VERSION = '4.0.5.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 4040000}
  FRAMEWORK_VERSION = '4.0.4.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 4030000}
  FRAMEWORK_VERSION = '4.0.3.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 4020000}
  FRAMEWORK_VERSION = '4.0.2.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 4010000}
  FRAMEWORK_VERSION = '4.0.1.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 4000000}
  FRAMEWORK_VERSION = '4.0.0.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 3010000}
  FRAMEWORK_VERSION = '3.0.1.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 3000000}
  FRAMEWORK_VERSION = '3.0.0.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 2090000}
  FRAMEWORK_VERSION = '2.0.9.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 2080000}
  FRAMEWORK_VERSION = '2.0.8.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 2070000}
  FRAMEWORK_VERSION = '2.0.7.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 2060000}
  FRAMEWORK_VERSION = '2.0.6.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 2050000}
  FRAMEWORK_VERSION = '2.0.5.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 2040000}
  FRAMEWORK_VERSION = '2.0.4.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 2030000}
  FRAMEWORK_VERSION = '2.0.3.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 2020000}
  FRAMEWORK_VERSION = '2.0.2.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 2010000}
  FRAMEWORK_VERSION = '2.0.1.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 2000000}
  FRAMEWORK_VERSION = '2.0.0.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 1080000}
  FRAMEWORK_VERSION = '1.0.8.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 1070000}
  FRAMEWORK_VERSION = '1.0.7.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 1060000}
  FRAMEWORK_VERSION = '1.0.6.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 1050000}
  FRAMEWORK_VERSION = '1.0.5.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 1040000}
  FRAMEWORK_VERSION = '1.0.4.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 1030000}
  FRAMEWORK_VERSION = '1.0.3.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 1020000}
  FRAMEWORK_VERSION = '1.0.2.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 1010000}
  FRAMEWORK_VERSION = '1.0.1.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 1000000}
  FRAMEWORK_VERSION = '1.0.0.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 999000}
  FRAMEWORK_VERSION = '0.999.000';
  {$endif}
  {$if LCL_FULLVERSION  = 998000}
  FRAMEWORK_VERSION = '0.998.000';
  {$endif}
  {$if LCL_FULLVERSION  = 994000}
  FRAMEWORK_VERSION = '0.994.000';
  {$endif}
  {$if LCL_FULLVERSION  = 988000}
  FRAMEWORK_VERSION = '0.988.000';
  {$endif}
  {$if LCL_FULLVERSION  = 966000}
  FRAMEWORK_VERSION = '0.966.000';
  {$endif}
  {$if LCL_FULLVERSION  = 944400}
  FRAMEWORK_VERSION = '0.944.400';
  {$endif}
  {$if LCL_FULLVERSION  = 933000}
  FRAMEWORK_VERSION = '0.933.000';
  {$endif}
  {$if LCL_FULLVERSION  = 922000}
  FRAMEWORK_VERSION = '0.922.000';
  {$endif}
  {$if LCL_FULLVERSION  = 910000}
  FRAMEWORK_VERSION = '0.910.000';
  {$endif}
  {$if LCL_FULLVERSION  = 900000}
  FRAMEWORK_VERSION = '0.900.000';
  {$endif}
  {$if LCL_FULLVERSION  = 899000}
  FRAMEWORK_VERSION = '0.899.000';
  {$endif}
  {$if LCL_FULLVERSION  = 888000}
  FRAMEWORK_VERSION = '0.888.000';
  {$endif}
  {$if LCL_FULLVERSION  = 855000}
  FRAMEWORK_VERSION = '0.855.000';
  {$endif}
  {$if LCL_FULLVERSION  = 822000}
  FRAMEWORK_VERSION = '0.822.000';
  {$endif}
  {$if LCL_FULLVERSION  = 810000}
  FRAMEWORK_VERSION = '0.810.000';
  {$endif}
  {$if LCL_FULLVERSION  = 788000}
  FRAMEWORK_VERSION = '0.788.000';
  {$endif}
  {$if LCL_FULLVERSION  = 777000}
  FRAMEWORK_VERSION = '0.777.000';
  {$endif}
  {$if LCL_FULLVERSION  = 755000}
  FRAMEWORK_VERSION = '0.755.000';
  {$endif}
  {$if LCL_FULLVERSION  = 744000}
  FRAMEWORK_VERSION = '0.744000';
  {$endif}
  {$if LCL_FULLVERSION  = 737000}
  FRAMEWORK_VERSION = '0.737.000';
  {$endif}
  {$if LCL_FULLVERSION  = 672000}
  FRAMEWORK_VERSION = '0.672.000';
  {$endif}
  {$if LCL_FULLVERSION  = 641000}
  FRAMEWORK_VERSION = '0.641.000';
  {$endif}
  {$if LCL_FULLVERSION  = 610000}
  FRAMEWORK_VERSION = '0.61.0000';
  {$endif}
  {$if LCL_FULLVERSION  = 560000}
  FRAMEWORK_VERSION = '0.56.0000';
  {$endif}
{$endif}

