{========================================================================================
  Include file : poci_lcllazarusversion
  Description : Pascal Object Compiler Informations

                Purpose a way to get compiler informations in builded project

  Author : Frédéric Libaud
  **************************************************************************************
  History
  --------------------------------------------------------------------------------------
  2024 03 07 - Création
 ========================================================================================}

{$ifdef LAZVER}
  {$if LCL_FULLVERSION = 3020000}
  FRAMEWORK_VERSION = '3.0.2.0000';
  {$endif}
  {$if LCL_FULLVERSION = 3000000}
  FRAMEWORK_VERSION = '3.0.0.0000';
  {$endif}
  {$if LCL_FULLVERSION = 2020006}
  FRAMEWORK_VERSION = '2.0.2.0006';
  {$endif}
  {$if LCL_FULLVERSION = 2020004}
  FRAMEWORK_VERSION = '2.0.2.0004';
  {$endif}
  {$if LCL_FULLVERSION = 2020002}
  FRAMEWORK_VERSION = '2.0.2.0002';
  {$endif}
  {$if LCL_FULLVERSION = 2020000}
  FRAMEWORK_VERSION = '2.0.2.0000';
  {$endif}
  {$if LCL_FULLVERSION = 2000012}
  FRAMEWORK_VERSION = '2.0.0.0012';
  {$endif}
  {$if LCL_FULLVERSION = 2000010}
  FRAMEWORK_VERSION = '2.0.0.0010';
  {$endif}
  {$if LCL_FULLVERSION = 2000008}
  FRAMEWORK_VERSION = '2.0.0.0008';
  {$endif}
  {$if LCL_FULLVERSION = 2000006}
  FRAMEWORK_VERSION = '2.0.0.0006';
  {$endif}
  {$if LCL_FULLVERSION = 2000004}
  FRAMEWORK_VERSION = '2.0.0.0004';
  {$endif}
  {$if LCL_FULLVERSION = 2000002}
  FRAMEWORK_VERSION = '2.0.0.0002';
  {$endif}
  {$if LCL_FULLVERSION = 1080004}
  FRAMEWORK_VERSION = '1.0.8.0004';
  {$endif}
  {$if LCL_FULLVERSION = 1080002}
  FRAMEWORK_VERSION = '1.0.8.0002';
  {$endif}
  {$if LCL_FULLVERSION = 1080000}
  FRAMEWORK_VERSION = '1.0.8.0000';
  {$endif}
  {$if LCL_FULLVERSION = 1060002}
  FRAMEWORK_VERSION = '1.0.6.0002';
  {$endif}
  {$if LCL_FULLVERSION = 1060000}
  FRAMEWORK_VERSION = '1.0.6.0000';
  {$endif}
  {$if LCL_FULLVERSION = 1040004}
  FRAMEWORK_VERSION = '1.0.4.0004';
  {$endif}
  {$if LCL_FULLVERSION = 1040002}
  FRAMEWORK_VERSION = '1.0.4.0002';
  {$endif}
  {$if LCL_FULLVERSION = 1040000}
  FRAMEWORK_VERSION = '1.0.4.0000';
  {$endif}
  {$if LCL_FULLVERSION = 1020006}
  FRAMEWORK_VERSION = '1.0.2.0006';
  {$endif}
  {$if LCL_FULLVERSION = 1020004}
  FRAMEWORK_VERSION = '1.0.2.0004';
  {$endif}
  {$if LCL_FULLVERSION = 1020002}
  FRAMEWORK_VERSION = '1.0.2.0002';
  {$endif}
  {$if LCL_FULLVERSION = 1020000}
  FRAMEWORK_VERSION = '1.0.2.0000';
  {$endif}
  {$if LCL_FULLVERSION = 1000014}
  FRAMEWORK_VERSION = '1.0.0.0014';
  {$endif}
  {$if LCL_FULLVERSION = 1000012}
  FRAMEWORK_VERSION = '1.0.0.0012';
  {$endif}
  {$if LCL_FULLVERSION = 1000010}
  FRAMEWORK_VERSION = '1.0.0.0010';
  {$endif}
  {$if LCL_FULLVERSION = 1000008}
  FRAMEWORK_VERSION = '1.0.0.0008';
  {$endif}
  {$if LCL_FULLVERSION = 1000006}
  FRAMEWORK_VERSION = '1.0.0.0006';
  {$endif}
  {$if LCL_FULLVERSION = 1000004}
  FRAMEWORK_VERSION = '1.0.0.0004';
  {$endif}
  {$if LCL_FULLVERSION = 1000002}
  FRAMEWORK_VERSION = '1.0.0.0002';
  {$endif}
  {$if LCL_FULLVERSION = 1000000}
  FRAMEWORK_VERSION = '1.0.0.0000';
  {$endif}
  {$if LCL_FULLVERSION = 0093002}
  FRAMEWORK_VERSION = '0.0.9.3002';
  {$endif}
  {$if LCL_FULLVERSION = 0092802}
  FRAMEWORK_VERSION = '0.0.9.2802';
  {$endif}
  {$if LCL_FULLVERSION = 0092800}
  FRAMEWORK_VERSION = '0.0.9.2800';
  {$endif}
  {$if LCL_FULLVERSION = 0092602}
  FRAMEWORK_VERSION = '0.0.9.2602';
  {$endif}
  {$if LCL_FULLVERSION = 0092600}
  FRAMEWORK_VERSION = '0.0.9.2600';
  {$endif}
  {$if LCL_FULLVERSION = 0092400}
  FRAMEWORK_VERSION = '0.0.9.2400';
  {$endif}
  {$if LCL_FULLVERSION = 0092200}
  FRAMEWORK_VERSION = '0.0.9.2200';
  {$endif}
  {$if LCL_FULLVERSION = 0092000}
  FRAMEWORK_VERSION = '0.0.9.2000';
  {$endif}
  {$if LCL_FULLVERSION = 0091800}
  FRAMEWORK_VERSION = '0.0.9.1800';
  {$endif}
  {$if LCL_FULLVERSION = 0091600}
  FRAMEWORK_VERSION = '0.0.9.1600';
  {$endif}
{$endif}


