{========================================================================================
  Include file : poci_typhonversions
  Description : Pascal Object Compiler Informations

                Purpose a way to get compiler informations in builded project

  Author : Frédéric Libaud
  **************************************************************************************
  History
  --------------------------------------------------------------------------------------
  2024 03 07 - Création
 ========================================================================================}

{$ifdef CT_VERSION}
  {$if CT_VERSION = 830}
  ENVIRONMENT_VERSION = '8.30';
  {$endif}
  {$if CT_VERSION = 820}
  ENVIRONMENT_VERSION = '8.20';
  {$endif}
  {$if CT_VERSION = 810}
  ENVIRONMENT_VERSION = '8.10';
  {$endif}
  {$if CT_VERSION = 800}
  ENVIRONMENT_VERSION = '8.00';
  {$endif}
  {$if CT_VERSION = 790}
  ENVIRONMENT_VERSION = '7.90';
  {$endif}
  {$if CT_VERSION = 780}
  ENVIRONMENT_VERSION = '7.80';
  {$endif}
  {$if CT_VERSION = 770}
  ENVIRONMENT_VERSION = '7.70';
  {$endif}
  {$if CT_VERSION = 760}
  ENVIRONMENT_VERSION = '7.60';
  {$endif}
  {$if CT_VERSION = 750}
  ENVIRONMENT_VERSION = '7.50';
  {$endif}
  {$if CT_VERSION = 740}
  ENVIRONMENT_VERSION = '7.40';
  {$endif}
  {$if CT_VERSION = 730}
  ENVIRONMENT_VERSION = '7.30';
  {$endif}
  {$if CT_VERSION = 720}
  ENVIRONMENT_VERSION = '7.20';
  {$endif}
  {$if CT_VERSION = 710}
  ENVIRONMENT_VERSION = '7.10';
  {$endif}
  {$if CT_VERSION = 700}
  ENVIRONMENT_VERSION = '7.00';
  {$endif}
  {$if CT_VERSION = 690}
  ENVIRONMENT_VERSION = '6.90';
  {$endif}
  {$if CT_VERSION = 680}
  ENVIRONMENT_VERSION = '6.80';
  {$endif}
  {$if CT_VERSION = 670}
  ENVIRONMENT_VERSION = '6.70';
  {$endif}
  {$if CT_VERSION = 660}
  ENVIRONMENT_VERSION = '6.60';
  {$endif}
  {$if CT_VERSION = 650}
  ENVIRONMENT_VERSION = '6.50';
  {$endif}
  {$if CT_VERSION = 640}
  ENVIRONMENT_VERSION = '6.40';
  {$endif}
  {$if CT_VERSION = 630}
  ENVIRONMENT_VERSION = '6.30';
  {$endif}
  {$if CT_VERSION = 620}
  ENVIRONMENT_VERSION = '6.20';
  {$endif}
  {$if CT_VERSION = 610}
  ENVIRONMENT_VERSION = '6.10';
  {$endif}
  {$if CT_VERSION = 600}
  ENVIRONMENT_VERSION = '6.00';
  {$endif}
  {$if CT_VERSION = 590}
  ENVIRONMENT_VERSION = '5.90';
  {$endif}
  {$if CT_VERSION = 580}
  ENVIRONMENT_VERSION = '5.80';
  {$endif}
  {$if CT_VERSION = 570}
  ENVIRONMENT_VERSION = '5.70';
  {$endif}
  {$if CT_VERSION = 560}
  ENVIRONMENT_VERSION = '5.60';
  {$endif}
  {$if CT_VERSION = 550}
  ENVIRONMENT_VERSION = '5.50';
  {$endif}
  {$if CT_VERSION = 540}
  ENVIRONMENT_VERSION = '5.40';
  {$endif}
  {$if CT_VERSION = 530}
  ENVIRONMENT_VERSION = '5.30';
  {$endif}
  {$if CT_VERSION = 520}
  ENVIRONMENT_VERSION = '5.20';
  {$endif}
  {$if CT_VERSION = 510}
  ENVIRONMENT_VERSION = '5.10';
  {$endif}
  {$if CT_VERSION = 500}
  ENVIRONMENT_VERSION = '5.00';
  {$endif}
  {$if CT_VERSION = 492}
  ENVIRONMENT_VERSION = '4.92';
  {$endif}
  {$if CT_VERSION = 490}
  ENVIRONMENT_VERSION = '4.90';
  {$endif}
  {$if CT_VERSION = 480}
  ENVIRONMENT_VERSION = '4.80';
  {$endif}
  {$if CT_VERSION = 470}
  ENVIRONMENT_VERSION = '4.70';
  {$endif}
  {$if CT_VERSION = 460}
  ENVIRONMENT_VERSION = '4.60';
  {$endif}
  {$if CT_VERSION = 450}
  ENVIRONMENT_VERSION = '4.50';
  {$endif}
  {$if CT_VERSION = 440}
  ENVIRONMENT_VERSION = '4.40';
  {$endif}
  {$if CT_VERSION = 430}
  ENVIRONMENT_VERSION = '4.30';
  {$endif}
  {$if CT_VERSION = 420}
  ENVIRONMENT_VERSION = '4.20';
  {$endif}
  {$if CT_VERSION = 410}
  ENVIRONMENT_VERSION = '4.10';
  {$endif}
  {$if CT_VERSION = 400}
  ENVIRONMENT_VERSION = '4.00';
  {$endif}
  {$if CT_VERSION = 310}
  ENVIRONMENT_VERSION = '3.10';
  {$endif}
  {$if CT_VERSION = 300}
  ENVIRONMENT_VERSION = '3.00';
  {$endif}
  {$if CT_VERSION = 290}
  ENVIRONMENT_VERSION = '2.90';
  {$endif}
  {$if CT_VERSION = 280}
  ENVIRONMENT_VERSION = '2.80';
  {$endif}
  {$if CT_VERSION = 270}
  ENVIRONMENT_VERSION = '2.70';
  {$endif}
  {$if CT_VERSION = 260}
  ENVIRONMENT_VERSION = '2.60';
  {$endif}
  {$if CT_VERSION = 250}
  ENVIRONMENT_VERSION = '2.50';
  {$endif}
  {$if CT_VERSION = 240}
  ENVIRONMENT_VERSION = '2.40';
  {$endif}
  {$if CT_VERSION = 230}
  ENVIRONMENT_VERSION = '2.30';
  {$endif}
  {$if CT_VERSION = 220}
  ENVIRONMENT_VERSION = '2.20';
  {$endif}
  {$if CT_VERSION = 210}
  ENVIRONMENT_VERSION = '2.10';
  {$endif}
  {$if CT_VERSION = 200}
  ENVIRONMENT_VERSION = '2.00';
  {$endif}
  {$if CT_VERSION = 180}
  ENVIRONMENT_VERSION = '1.80';
  {$endif}
  {$if CT_VERSION = 170}
  ENVIRONMENT_VERSION = '1.70';
  {$endif}
  {$if CT_VERSION = 160}
  ENVIRONMENT_VERSION = '1.60';
  {$endif}
  {$if CT_VERSION = 150}
  ENVIRONMENT_VERSION = '1.50';
  {$endif}
  {$if CT_VERSION = 140}
  ENVIRONMENT_VERSION = '1.40';
  {$endif}
  {$if CT_VERSION = 130}
  ENVIRONMENT_VERSION = '1.30';
  {$endif}
  {$if CT_VERSION = 120}
  ENVIRONMENT_VERSION = '1.20';
  {$endif}
  {$if CT_VERSION = 110}
  ENVIRONMENT_VERSION = '1.10';
  {$endif}
  {$if CT_VERSION = 100}
  ENVIRONMENT_VERSION = '1.00';
  {$endif}
  {$if CT_VERSION = 0999}
  ENVIRONMENT_VERSION = '0.999';
  {$endif}
  {$if CT_VERSION = 0998}
  ENVIRONMENT_VERSION = '0.998';
  {$endif}
  {$if CT_VERSION = 0994}
  ENVIRONMENT_VERSION = '0.994';
  {$endif}
  {$if CT_VERSION = 0988}
  ENVIRONMENT_VERSION = '0.988';
  {$endif}
  {$if CT_VERSION = 0966}
  ENVIRONMENT_VERSION = '0.966';
  {$endif}
  {$if CT_VERSION = 0944}
  ENVIRONMENT_VERSION = '0.944';
  {$endif}
  {$if CT_VERSION = 0933}
  ENVIRONMENT_VERSION = '0.933';
  {$endif}
  {$if CT_VERSION = 0922}
  ENVIRONMENT_VERSION = '0.922';
  {$endif}
  {$if CT_VERSION = 0910}
  ENVIRONMENT_VERSION = '0.910';
  {$endif}
  {$if CT_VERSION = 0900}
  ENVIRONMENT_VERSION = '0.900';
  {$endif}
  {$if CT_VERSION = 0899}
  ENVIRONMENT_VERSION = '0.899';
  {$endif}
  {$if CT_VERSION = 0888}
  ENVIRONMENT_VERSION = '0.888';
  {$endif}
  {$if CT_VERSION = 0855}
  ENVIRONMENT_VERSION = '0.855';
  {$endif}
  {$if CT_VERSION = 0822}
  ENVIRONMENT_VERSION = '0.822';
  {$endif}
  {$if CT_VERSION = 0810}
  ENVIRONMENT_VERSION = '0.810';
  {$endif}
  {$if CT_VERSION = 0788}
  ENVIRONMENT_VERSION = '0.788';
  {$endif}
  {$if CT_VERSION = 0777}
  ENVIRONMENT_VERSION = '0.777';
  {$endif}
  {$if CT_VERSION = 0755}
  ENVIRONMENT_VERSION = '0.755';
  {$endif}
  {$if CT_VERSION = 0744}
  ENVIRONMENT_VERSION = '0.744';
  {$endif}
  {$if CT_VERSION = 0737}
  ENVIRONMENT_VERSION = '0.737';
  {$endif}
  {$if CT_VERSION = 0672}
  ENVIRONMENT_VERSION = '0.672';
  {$endif}
  {$if CT_VERSION = 0641}
  ENVIRONMENT_VERSION = '0.641';
  {$endif}
  {$if CT_VERSION = 0610}
  ENVIRONMENT_VERSION = '0.610';
  {$endif}
  {$if CT_VERSION = 0566}
  ENVIRONMENT_VERSION = '0.566';
  {$endif}
{$endif}

